import { pinyinSyllables } from "../data/pinyin";
import { formatPinyin } from "../format/pinyin";
import { NativeQuery, NativeQueryState } from "./interfaces";
import { StringPrefixQuery } from "./prefix";

class PinyinPrefixQuery extends StringPrefixQuery {
  constructor(private query: string) {
    super(query);
  }

  transition(from: NativeQueryState, by: number): NativeQueryState {
    const nextState = super.transition(from, by);

    if (nextState === -1) {
      if (0x31 <= by && by <= 0x35) {
        // ignore tone numbers if the query doesn't have them
        // (but any tone numbers present in the query will not be ignored)
        return from;
      } else if (by === 0x75) {
        // allow u to match v as well (not currently generated by the generator however)
        return super.transition(from, 0x76);
      }
    }

    return nextState;
  }

  toString() {
    return ` “${formatPinyin(this.query)}” `;
  }

  kind() {
    return "pinyin";
  }
}

export function processPinyin(query: string): NativeQuery | null {
  query = query.toLowerCase().replace(/\s+/g, "");
  if (query.length === 0) {
    return null;
  }

  if (isPinyinPrefix(query)) {
    return new PinyinPrefixQuery(query);
  } else {
    return null;
  }
}

function isPinyinPrefix(query: string): boolean {
  if (query.length === 0) {
    return true;
  }

  let current = pinyinTrie;

  for (let i = 0; i < query.length; i++) {
    const char = query[i];
    if (!current.children.has(char)) {
      if ("12345".includes(char)) {
        // skip tone numbers
        continue;
      } else {
        return false;
      }
    }
    current = current.children.get(char)!;

    if (current.isEndOfSyllable) {
      if (isPinyinPrefix(query.substring(i + 1))) {
        return true;
      }
    }
  }

  return true;
}

class TrieNode {
  children: Map<string, TrieNode> = new Map();
  isEndOfSyllable: boolean = false;
}

const pinyinTrie = new TrieNode();

for (const syllable of pinyinSyllables) {
  let currentNode = pinyinTrie;
  for (const char of syllable) {
    if (!currentNode.children.has(char)) {
      currentNode.children.set(char, new TrieNode());
    }
    currentNode = currentNode.children.get(char)!;
  }
  currentNode.isEndOfSyllable = true;
}
